name: Auto Generate and Replace Reference Files

on:
  push:
    branches:
      - develop

jobs:
  generate_reference-and-commit:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: generate reference
      run: |
        sudo gem install jazzy
        ./generate_reference.sh

    - name: Setup git
      env:
          EMAIL: ${{ secrets.EMAIL }}
      run: |
        git config --global user.email "$EMAIL"
        git config --global user.name "ncmbadmin"
        
    - name: Commit docs
      run: |
        if ! git diff --exit-code --quiet
        then
          git add .
          git commit -m "Auto replace reference files"
          git pull
          git push origin develop
        fi
  
    - name: zip docs
      run: zip -r docs.zip docs/

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: docs
        path: docs.zip