name: Swift

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v3
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_14.2.app/Contents/Developer'
    - name: Build
      run: xcodebuild
           -scheme NCMB
           CODE_SIGNING_ALLOWED=NO
           -configuration Debug
           build
    - name: Run tests
      run: xcodebuild
           -scheme NCMBTests
           -sdk iphonesimulator
           -destination 'platform=iOS Simulator,name=iPhone 14'
           clean test
