name: Swift

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Swift
      uses: swift-actions/setup-swift@v1
    - name: Get swift version
      run: swift --version
    - name: Build
      run: swift build
    - name: Run tests
      run: swift test
