name: Swift

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v3
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_14.1.0.app/Contents/Developer'
    - name: Build
      run: xcodebuild
           -scheme NCMB
           -sdk iphonesimulator
           -configuration Debug
           build
    - name: Run tests
      run: xcodebuild
           -scheme NCMBTests
           -sdk iphonesimulator
           -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max,OS=16.1'
           clean test
